### ISSUE TITLE
Invalid ranges during formatting ...

### ISSUE THREAD

**Issue by matej21** [JanTvrdik/intellij-latte#22]
```
[10470467]  ERROR - .formatting.InitialInfoBuilder - IdeaLoggingEvent[message=Invalid ranges during formatting in Language: Latte, throwable=java.lang.Throwable
        at com.jantvrdik.intellij.latte.formatter.LatteFormattingModelBuilder.createModel(LatteFormattingModelBuilder.java:1)
        at com.intellij.formatting.InitialInfoBuilder.assertInvalidRanges(InitialInfoBuilder.java:517)
        at com.intellij.formatting.WhiteSpace.append(WhiteSpace.java:127)
        at com.intellij.formatting.InitialInfoBuilder.a(InitialInfoBuilder.java:201)
        at com.intellij.formatting.InitialInfoBuilder.a(InitialInfoBuilder.java:320)
        at com.intellij.formatting.InitialInfoBuilder.iteration(InitialInfoBuilder.java:146)
        at com.intellij.formatting.FormatProcessor$WrapBlocksState.doIteration(FormatProcessor.java:1409)
        at com.intellij.formatting.FormatProcessor$State.iteration(FormatProcessor.java:1339)
        at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:283)
        at com.intellij.formatting.FormatterImpl.a(FormatterImpl.java:540)
        at com.intellij.formatting.FormatterImpl.getLineIndent(FormatterImpl.java:599)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$7.doPerform(CodeStyleManagerImpl.java:414)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$7.doPerform(CodeStyleManagerImpl.java:406)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerRunnable.perform(CodeStyleManagerRunnable.java:109)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.getLineIndent(CodeStyleManagerImpl.java:416)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.getLineIndent(CodeStyleManagerImpl.java:425)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleFacadeImpl.getLineIndent(CodeStyleFacadeImpl.java:53)
        at com.intellij.codeInsight.editorActions.SmartIndentingBackspaceHandler.doBeforeCharDeleted(SmartIndentingBackspaceHandler.java:63)
        at com.intellij.codeInsight.editorActions.AbstractIndentingBackspaceHandler.beforeCharDeleted(AbstractIndentingBackspaceHandler.java:42)
        at com.intellij.codeInsight.editorActions.SmartIndentingBackspaceHandler.beforeCharDeleted(SmartIndentingBackspaceHandler.java:37)
        at com.intellij.codeInsight.editorActions.BackspaceHandler.handleBackspace(BackspaceHandler.java:95)
        at com.intellij.codeInsight.editorActions.BackspaceHandler.executeWriteAction(BackspaceHandler.java:61)
        at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:56)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
        at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:49)
        at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:206)
        at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
        at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:38)
        at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:203)
        at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:345)
        at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:425)
        at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:336)
        at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:327)
        at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:200)
        at com.intellij.codeInsight.lookup.impl.BackspaceHandler.doExecute(BackspaceHandler.java:38)
        at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
        at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
        at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
        at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
        at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
        at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.c(IdeKeyEventDispatcher.java:485)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by matej21** [comment]
fixed by 8ff7eec851
